<?php
// Add Some Code Here for design
/**
 * @var \Mageplaza\GiftCard\Block\GiftCard\Mytab $block
 */
$balance = $block->getGCCBalance();
//configuration Allow Redeem Gift Card là NO thì sẽ ko hiện field này
$statusRedeem = $block->getStatusRedeem();
?>
<div class="block block-dashboard-info">
        <div class="block-title"><strong>Gift Card Information</strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span>Balance</span>
            </strong>
            <div class="box-content">
                <p>
                    <?php
                        echo $balance;
                    ?>
                </p>
            </div>
        </div>
        <?php
        if($statusRedeem == 1) {
        ?>
        <div class="box box-infomation">
            <strong class="box-title">
                <span>Redeem</span>
            </strong>
            <div class="box-content">
                <form action="<?php echo $block->getUrl('giftcard/customer/redeem') ?>" class="form" id="my-form" method="post" data-mage-init='{"validation":{"rules": {"field-3": {"required":true}}}}'>
                    <div style="display: flex">
                        <fieldset class="fieldset">
                            <div class="field name required">
                                <div class="control">
                                    <input placeholder="Enter gift card code" name="giftcard_code" id="giftcard_code" title="giftcard_code" value="" type="text" class="required-entry input-text"/>
                                </div>
                            </div>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" title="Submit" class="action submit primary">
                                    <span>Redeem</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
<!--            <div class="box-actions">-->
<!--                <a class="action edit" href="http://localhost.com/ce234/newsletter/manage/"><span>Edit</span></a>-->
<!--            </div>-->
            </div>
        <?php
        }
        ?>
    </div>

    <div class="block-title"><strong>History</strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span>Balance</span>
            </strong>
            <div class="box-content">
                <p>
                    <?php
                    echo $balance;
                    ?>
                </p>
            </div>
        </div>
    </div>

</div>

