<?php
// Add Some Code Here for design
/**
 * @var \Mageplaza\GiftCard\Block\GiftCard\Mytab $block
 */
$balance = $block->getGCCBalance();
//configuration Allow Redeem Gift Card là NO thì sẽ ko hiện field này
$statusRedeem = $block->getStatusRedeem();
//$gCHistory = $block->getHistory();

$gCHistory = $block->getHistoryCollection();
//echo "<pre>";
//print_r($test->getData());
//echo "</pre>";
//die();
?>
<div class="block block-dashboard-info">
        <div class="block-title"><strong>Gift Card Information</strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span>Balance</span>
            </strong>
            <div class="box-content">
                <p>
                    <?php
                        echo $balance;
                    ?>
                </p>
            </div>
        </div>
        <?php if($statusRedeem == 1): ?>
        <div class="box box-infomation">
            <strong class="box-title">
                <span>Redeem</span>
            </strong>
            <div class="block">
                <form action="<?php echo $block->getUrl('giftcard/customer/redeem') ?>" class="form" id="my-form" method="post" data-mage-init='{"validation":{"rules": {"field-3": {"required":true}}}}'>
                    <div style="display: flex">
                                <div class="control">
                                    <input placeholder="Enter gift card code" name="giftcard_code" id="giftcard_code" title="giftcard_code" value="" type="text" class="required-entry input-text"/>
                                </div>
                        <div class="actions">
                            <div class="primary">
                                <button type="submit" title="Submit" class="action submit primary">
                                    <span>Redeem</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            </div>
        <?php endif ?>
    </div>

    <div class="block-title"><strong>History</strong></div>
    <div class="block-content">
        <div class="block">
            <div class="content">
                <?php if ($gCHistory && count($gCHistory)) : ?>
                    <div class="table-wrapper orders-history">
                        <table class="data table table-order-items history" id="my-orders-table">
                            <thead>
                            <tr>
                                <th scope="col" class="col id">Date</th>
                                <th scope="col" class="col date">Code</th>
                                <th scope="col" class="col shipping">Amount</th>
                                <th scope="col" class="col total">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($gCHistory as $gCHistory) : ?>
                                <tr>
                                    <td  class="col date"><?php echo $block->setDate($gCHistory['action_time']) ?></td>
                                    <td class="col code"><?php echo $block->getGiftCardCode($gCHistory['giftcard_id']) ?></td>
                                    <td class="col action"><?php echo $block->setCurrency($gCHistory['amount']) ?></td>
                                    <td class="col amount"><?php echo $gCHistory['action'] ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <?php if ($block->getPagerHtml()): ?>
                        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
                    <?php endif ?>
                <?php else: ?>
                    <div class="message info empty"><span><?php echo __('No any record.'); ?></span></div>
                <?php endif ?>
            </div>
        </div>
    </div>

</div>

